### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by SherlocksHat** [adde88/ManaToolkit#7]
ManaToolkit has been successfully installed on my Nano, but wont start with the default hostapd config, or even a simple config. 

I even tried factory reset, and re-installing it - same issue.

**Comment by mattlawer** [comment]
Also tried to install but on a Tetra and at first ManaToolkit.sh gave me an error because I didn't installed the 'ip' command, fixed it with `opkg install ip` but now I see that the launch-mana can't find `sslstrip2` and `dns2proxy`.
    
    /usr/sbin/launch-mana: line 260: cd: /usr/share/mana-toolkit/sslstrip-hsts/sslstrip2/: No such file or directory
    /usr/sbin/launch-mana: line 263: cd: /usr/share/mana-toolkit/sslstrip-hsts/dns2proxy/: No such file or directory
    
And after looking in the sslstrip2_1.0-1_ar71xx.ipk downloaded from the hostapd-mana postinst-pkg script I found a README.md file stating:

---

SSLstrip+
========

This is just a mirror of the original SSLstrip+ code by Leonardo Nve, which had to be taken down because of a gag order.

**For this to work you also need a DNS server that reverses the changes made by the proxy, you can find it at https://github.com/singe/dns2proxy**

---

I think the original sslstrip2 repo has been taken down and it's the issue in the current mana install script.


I managed to fix the missing sslstrip2/dns2proxy by manually cloning their respective git repos.
    
    opkg update && opkg install git
    git clone git://github.com/byt3bl33d3r/sslstrip2.git /usr/share/mana-toolkit/sslstrip-hsts/sslstrip2
    git clone git://github.com/singe/dns2proxy.git /usr/share/mana-toolkit/sslstrip-hsts/dns2proxy

Now I get the `rfkill: Cannot open RFKILL control device` error when running launch-mana and `Exiting! (Error code: 9)`.
Found out that Error code 9 was caused by net-creds. The net-crews binary is defined as
    
    netcreds_bin="/usr/share/mana-toolkit/net-creds/net-creds.py"
    
And /usr/share/mana-toolkit/net-creds didn't exist on my device so I installed it with:
    
    git clone git://github.com/DanMcInerney/net-creds.git /usr/share/mana-toolkit/net-creds
    
and VOILA!

Mana Toolkit has started successfully and is now running in the background.
Run kill-mana to stop Mana Toolkit.

**Comment by ghost** [comment]
sir may i know how to install manatoolkit i tryed so many ways but it not at all installing in my kalimachine

**Comment by adde88** [comment]
> sir may i know how to install manatoolkit i tryed so many ways but it not at all installing in my kalimachine

Your "Kali machine"? I'm sorry, but this is ManaToolkit for the WiFi Pineapple.
